grafanadi and lunettes-chart increase delay start
alipay/container-observability-service pull request #77
Opened 2024-02-06 06:43 UTC by zhangtong007

Before modification, grafanadi and lunettes-chart may restart due to slow readiness of the es cluster.
![test](https://github.com/alipay/container-observability-service/assets/91560756/478e46a0-392a-4609-ac74-9e203d66c20c)

After that, there will no longer be a restart, but wait for the es cluster to be ready before staring their service.
![test](https://github.com/alipay/container-observability-service/assets/91560756/954b8991-2145-4808-b415-84cb9fece196)

2024-02-06 07:29 UTC, linuzb commented on deploy/helm/lunettes/templates/grafanadi/grafanadi-deploy.yaml
> +            http://es-cluster-svc.lunettes:9200 \
use `http://es-cluster-svc.{{ .Values.namespace }}:9200` instead of `http://es-cluster-svc.lunettes:9200`, because namespace maybe different

2024-02-06 07:29 UTC, linuzb commented on deploy/helm/lunettes/templates/grafanadi/grafanadi-deploy.yaml
> +            status_code=`curl -s --connect-timeout 3 --max-time 5 \
you can ref https://github.com/alipay/container-observability-service/blob/e955cefb2ba9ffb21f5e0c65f937a6cf044be146/.github/workflows/e2e-test.yml#L58-L65 to check es is ready or not

2024-02-20 11:43 UTC, d3c3mber requested changes
.

2024-02-20 11:44 UTC, d3c3mber commented on deploy/helm/lunettes/templates/grafanadi/grafanadi-deploy.yaml
> +          while true;
can you please merge these two checking loops into one

2024-02-24 12:30 UTC, zhangtong007 commented
> .

done

2024-02-24 13:19 UTC, d3c3mber approved these changes

2024-02-28 11:03 UTC, linuzb approved these changes
LGTM

2024-02-28 11:03 UTC, merged